/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    'Save File Empty.': '存档是空的',
    'Collect Limes': '收集酸橙',
    'Limes': '酸橙',
    'Main Square': '主广场',
    'Market': '市场',
    'Max Juicers': '榨汁机上限',
    'Max Peelers': '削皮器上限',
    'Mega Coins': '超级金币',
    'More Land': '更多土地',
    'Maxed Purchases Shown': '显示的最大购买次数',
    'Multitasking': '多任务处理',
    'Nourishment': '营养',
    'Info': '信息',
    'Intelligence': '智力',
    'Inventory': '库存',
    'Juice': '果汁',
    'John McLime': '约翰·麦克莱姆',
    'Keen Eye': '敏锐的目光',
    'Lime Inc.': '酸橙公司',
    'Look Around': '环视四周',
    'Decrease': '减少',
    'Decrease Juice Sold': '减少果汁销售',
    'On Limes': '酸橙',
    'Options': '选项',
    'Patrician Area': '贵族区',
    'Option to deliver maximum juice': '提供最大果汁的选项',
    'Peeled Limes': '去皮酸橙',
    'Pay Employee Their Wages': '支付员工工资',
    'Skills': '技能',
    'Start Task': '开始任务',
    'Stats': '统计',
    'Coins': '金币',
    'Click the application to accept.': '单击应用程序以接受。',
    'Check Results': '检查结果',
    'Convert Coins': '转换金币',
    'Completed Skills Shown': '显示完成的技能',
    'Collect limes without the pesky clicking': '无需烦人的点击即可收集酸橙',
    'Collect as many limes as possible before time runs out!': '在时间用完之前收集尽可能多的酸橙！',
    'Couldn\'t find any limes...': '找不到任何酸橙...',
    'Credit Score': '信用评分',
    'Currency Brokers': '货币经纪人',
    'Buy Shoes': '购买鞋子',
    'Buy More Land': '购买更多土地',
    'Buy Another Map': '购买另一张地图',
    'Buy Big Gloves': '购买大手套',
    'Buy Manuscripts': '购买手稿',
    'Click the \'Teach\' button to start a timer.': '单击“教学”按钮以启动计时器。',
    'Convert Coins to Alpha Coins': '将金币转换为阿尔法金币',
    'Convince the country that juice can be added to anything!': '说服这个国家果汁可以添加到任何东西中！',
    'Decrease Lakes': '减少湖泊',
    'Eat Food': '吃食物',
    'Earn Respect': '赢得尊重',
    'Export Code': '导出代码',
    'Export Game': '导出存档',
    'Express Delivery': '快速传送',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',

    //树游戏
    'Loading...': '加载中...',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "(-": "(-",
    "(+": "(+",
    "(": "(",
    "-": "-",
    "+": "+",
    " ": " ",
    ": ": "： ",
    "\n": "",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    "Currently: ": "当前: ",
    "Current Employees: ": "当前员工: ",
    'Buy A ': '购买一个 ',
    "Current increase: ": "当前增加: ",
    "Current maximum: ": "当前最大值：",
    "Current speed: ": "当前速度：",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    ":": "：",
    "：": "：",
    ": ": "： ",
    "： ": "： ",
    "/s)": "/s)",
    "/s": "/s",
    ")": ")",
    "%": "%",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": " ",
    "\n": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
    [/^Collect ([\d\.,]+) Coins.$/, '收集 $1 金币。'],
    [/^Price: ([\d\.,]+) Coins$/, '价格: $1 金币'],
    [/^Price: ([\d\.,]+) Alpha Coins$/, '价格: $1 阿尔法金币'],
    [/^Price: ([\d\.,]+) Mega Coins$/, '价格: $1 超级金币'],
    [/^Currently (.+) \- (.+) Coins$/, '当前 $1 \- $2 金币'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^(\d+) Royal points$/, '$1 皇家点数'],
    [/^Cost: (\d+) RP$/, '成本：$1 皇家点数'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);