/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    'Save File Empty.': '存档是空的',
    'Collect Limes': '收集酸橙',
    'Limes': '酸橙',
    'Main Square': '主广场',
    'Market': '市场',
    'Max Juicers': '榨汁机上限',
    'Max Peelers': '削皮器上限',
    'Mega Coins': '超级硬币',
    'More Land': '更多土地',
    'Maxed Purchases Shown': '显示的最大购买次数',
    'Multitasking': '多任务处理',
    'Nourishment': '营养',
    'Info': '信息',
    'Intelligence': '智力',
    'Inventory': '库存',
    'Juice': '果汁',
    'John McLime': '约翰·麦克莱姆',
    'Keen Eye': '敏锐的目光',
    'Lime Inc.': '酸橙公司',
    'Look Around': '环视四周',
    'Decrease': '减少',
    'Decrease Juice Sold': '减少果汁销售',
    'On Limes': '酸橙',
    'Options': '选项',
    'Patrician Area': '贵族区',
    'Option to deliver maximum juice': '提供最大果汁的选项',
    'Peeled Limes': '去皮酸橙',
    'Pay Employee Their Wages': '支付员工工资',
    'Skills': '技能',
    'Start Task': '开始任务',
    'Stats': '统计',
    'Coins': '硬币',
    'Click the application to accept.': '单击应用程序以接受。',
    'Check Results': '检查结果',
    'Convert Coins': '转换硬币',
    'Completed Skills Shown': '显示完成的技能',
    'Collect limes without the pesky clicking': '无需烦人的点击即可收集酸橙',
    'Collect as many limes as possible before time runs out!': '在时间用完之前收集尽可能多的酸橙！',
    'Couldn\'t find any limes...': '找不到任何酸橙...',
    'Credit Score': '信用评分',
    'Currency Brokers': '货币经纪人',
    'Buy Shoes': '购买鞋子',
    'Buy More Land': '购买更多土地',
    'Buy Another Map': '购买另一张地图',
    'Buy Big Gloves': '购买大手套',
    'Buy Manuscripts': '购买手稿',
    'Click the \'Teach\' button to start a timer.': '单击“教学”按钮以启动计时器。',
    'Convert Coins to Alpha Coins': '将硬币转换为阿尔法硬币',
    'Convince the country that juice can be added to anything!': '说服这个国家果汁可以添加到任何东西中！',
    'Decrease Lakes': '减少湖泊',
    'Eat Food': '吃食物',
    'Earn Respect': '赢得尊重',
    'Export Code': '导出代码',
    'Export Game': '导出存档',
    'Express Delivery': '快速交付',
    'Science': '科学',
    'Sell Juice': '出售果汁',
    'Sell Max Juice': '出售最大果汁',
    'Sell Your Limes': '出售你的酸橙',
    'Search For Specialised Workers': '寻找专业工人',
    'Sharper Peelers': '更锋利的削皮器',
    'Use Peeler': '使用削皮器',
    'Use Knife': '使用刀',
    'Wallet': '钱包',
    'Watertight Seal': '防水密封',
    'You can only spend this money once you arrive': '这些钱只能在你到达之后才能花',
    'You are in a lime forest.': '你在一片酸橙林中。',
    'Your employee learns from your abilities.': '你的员工从你的能力中学习。',
    'Disease Control': '疾病控制',
    'No Symbols': '无符号',
    'Small': '小',
    'Large': '大',
    'Symbols': '符号',
    'Better Transport': '更好的运输',
    'Big Gloves': '大手套',
    'Bigger Map': '更大的地图',
    'Benevolence': '善心',
    'Bigger Wallet': '更大的钱包',
    'Billboard': '广告牌',
    'Respect +50': '尊重 +50',
    'Respect increase': '尊重增加',
    'Respect Milestones': '尊重里程碑',
    'Robe': '长袍',
    'Rotten Limes': '烂酸橙',
    'Rotten Wisdom': '腐烂的智慧',
    'Rule': '规则',
    'Rule: Random empty spot': '规则：随机空位',
    'Upgrades': '升级',
    'Use Juicer': '使用榨汁机',
    'Unlock currency brokers': '解锁货币经纪人',
    'Unlock Permanance': '解锁永久',
    'Unlock Pinning Actions': '解锁固定操作',
    'Unlock the ability to hire currency brokers in the Hiring Area.': '解锁在招聘区域雇用货币经纪人的能力。',
    'Unlock Swamp Area': '解锁沼泽区域',
    'Unlock something special for completing this!': '解锁一些特别的东西来完成这个！',
    'You found something!': '你发现了什么！',
    'Auto Collect': '自动收集',
    'Auto': '自动',
    'Applicant Speed': '申请人速度',
    'Applicant Fee': '申请人费用',
    'Alpha Version': 'Alpha版本',
    'Advertising Manager': '广告经理',
    'Access the Currency Exchange market': '进入货币兑换市场',
    'The knife isnt gonna \'cut\' it': '刀不会“切”它',
    'The more you raise the price, the more it takes to convince the customer to still buy': '提价越多，就越需要说服客户继续购买',
    'The search gets more difficult the more you find': '你找到的越多，搜索就越困难',
    'There must be more *than* this town...': '一定有*多于*这个镇......',
    'There must be more to this town...': '这个小镇一定还有更多……',
    'Think about those less fortuanate than you - unlocks Benevolence.': '想想那些比你不幸的人——解锁仁慈。',
    'This fee seems a little unfair!': '这个收费好像有点不公平！',
    'Tome': '巨著',
    'Tomes can teach you new skills!': '巨著可以教你新技能！',
    'Trade': '贸易',
    'Transfer Alpha Coins': '转账阿尔法硬币',
    'Transfer Coins': '转账硬币',
    'Reset': '重置',
    'Reset Game': '重置游戏',
    'Research': '研究',
    'You use 1 food point per skill level.': '每升一级，你使用 1 个食物点。',
    'You Will Be Rewarded 1 Coin': '您将获得 1 个硬币的奖励',
    'You Will Get 1 Coins': '您将获得 1 硬币',
    'Add a new delivery type': '添加新的交付类型',
    'Add a new rule for your advertising manager': '为您的广告经理添加新规则',
    'Advertise your lime business': '宣传您的酸橙业务',
    'All purchases with red buttons stay with you after travels': '旅行后所有带有红色按钮的购买都会留在您身边',
    'Allow the toggling of skills': '允许切换技能',
    'Alpha Coins': '阿尔法硬币',
    'And if transfer amount is under 5': '如果转账金额低于 5',
    'Applicant Alpha Coin Transfer Amount': '申请阿尔法币转账金额',
    'Aquire Researchers': '收购研究人员',
    'Auto advertise if speed is over 30 seconds': '如果速度超过 30 秒，则自动做广告',
    'Map Of The Town': '城镇地图',
    'Manuscripts': '手稿',
    'Learn A New Skill': '学习一项新技能',
    'Juicer': '榨汁机',
    'Juice Price Permanance': '果汁价格不变',
    'Increase Lakes': '增加湖泊',
    'Juice price is saved after travelling.': '旅行后保存果汁价格。',
    'Standard Delivery': '标准交付',
    'Smarter Advertising Manager': '更智能的广告经理',
    'Research Better Advertising Methods': '研究更好的广告方法',
    'Quit': '退出',
    'Purchase a warehouse for your tools': '为您的工具购买仓库',
    'Plebian Area': '平民区',
    'Peeler': '削皮器',
    'Maybe I should keep looking around...': '也许我应该继续四处看看......',
    'Extreme Bulk Buying': '极端批量购买',
    'Doubles advertising speed': '广告速度翻倍',
    'Double auto collect rate': '双倍自动收集率',
    'Decrease Minimum': '减少最小值',
    'Decrease Maximum': '减少最大值',
    'Decreases peeled limes needed to make juice by 1.': '将制作果汁所需的去皮酸橙减少 1。',
    'You see a nearby market.': '你看到附近的一个市场。',
    'Triples advertising speed': '三倍广告速度',
    'Travelling': '旅行中',
    'Travel': '旅行',
    'Teach Employee': '教员工',
    'Tasks': '任务',
    'Surveying': '测量',
    'Take on a manager to help you advertise for brokers': '聘请经理帮助您为经纪人做广告',
    'The civilians in the swamp have lime disease too!': '沼泽里的平民也有酸橙病！',
    'Transfer money to a bank account in the next town': '转账到隔壁镇的银行账户',
    'Pin applications here': '在此处固定应用程序',
    'Pay with mega coins': '用超级硬币支付',
    'On Peeled Limes': '在去皮的酸橙',
    'Nutritionist': '营养师',
    'Modern': '现代',
    'Knife': '刀',
    'Increase Maximum': '增加最大值',
    'Increase Minimum': '增加最小值',
    'Increase Juice Sold': '提高果汁销售',
    'Increase Juice Price': '提高果汁价格',
    'Increase eating speed': '提高进食速度',
    'You find a merchant willing to buy limes.': '你找到一个愿意购买酸橙的商人。',
    'Travel To Next Village': '前往下一个村庄',
    'Start Simulation': '开始模拟',
    'Peelers can slice faster!': '削皮器可以更快地切片！',
    'Pay the entry fee to become a bulk buyer': '支付入场费成为大宗买家',
    'Normal bulk buying isn\'t enough!': '普通的批量购买是不够的！',
    'National Juice Marketing': '全国果汁营销',
    'Make currency conversion a togglable task': '使货币转换成为可切换的任务',
    'Make \'Increase juice price\' stay after travelling!': '旅行后留下“提高果汁价格”！',
    'Limebidextrous': '酸橙灵巧',
    'Knifebidextrous': '灵巧的刀法',
    'Increase': '增加',
    'Increase auto collect duration': '增加自动收集持续时间',
    'In Desktop Mode': '在桌面模式下',
    'Import Game': '导入存档',
    'Hiring Area': '招聘区域',
    'Hide Rotten Limes': '隐藏腐烂的酸橙',
    'Hire A Nutritionist': '聘请营养师',
    'You find a merchant selling various items.': '你找到一个商人出售各种物品。',
    'Get double the nutrition from eating': '从饮食中获得双倍的营养',
    'Get instant access to mega coins': '即时访问超级硬币',
    'Giant Map': '巨型地图',
    'Guaranteed to make you look rich!': '保证让你看起来很有钱！',
    'Hand Out Leaflets': '分发传单',
    'Help the citizens quarantine from Lime Disease': '帮助公民隔离酸橙病',
    'Helps you pick up double limes!': '帮你捡起双倍酸橙！',
    'Increase Credit Score': '提高信用评分',
    'Increase respect change from helping civilians with more lakes.': '通过帮助拥有更多湖泊的平民来增加尊重变化。',
    'Forest': '森林',
    'General Store': '杂货店',
    'Get better at finding limes / rotten limes.': '更好地寻找酸橙/腐烂的酸橙。',
    'Increase disease tiles by 1.': '将疾病板块增加 1。',
    'Auto advertise unless speed is under 30 seconds.': '自动广告，除非速度低于 30 秒。',
    'Increases max Mega Coins in the bank.': '增加银行中的最大超级硬币。',
    'Auto Converter': '自动转换器',
    'Auto Place A Civilian': '自动放置一个平民',
    'Automatically collects limes at 1': '在 1 时自动收集酸橙',
    'Bachelors Degree In Finance': '金融学学士学位',
    'Bar Percent Hidden': '隐藏百分比栏',
    'Bar Percent Shown': '显示百分比栏',
    'Basic Employees': '基本员工',
    'Basket': '篮子',
    'Baskets collect 5 Limes per minute each.': '每个篮子每分钟收集 5 个酸橙。',
    'Baskets collect up to 25 Limes each.': '每个篮子最多可收集 25 个酸橙。',
    'Better Training': '更好的培训',
    'Bulk Buying': '批量购买',
    'Bulk Peelers Storage': '散装去皮机存储',
    'Bulk Juicers Storage': '散装榨汁机存储',
    'Bulk Storage': '大容量存储',
    'Buy a conscience': '买一个良心',
    'Delivery Manager': '交付经理',
    'Disables the Collect Limes button': '禁用收集酸橙按钮',
    '\'Earn\' A Bachelors Degree In Finance': '“获得”金融学士学位',
    '\'Squeeze\' more money from your customers': '从客户那里“榨取”更多的钱',
    'You Learned Intelligence!': '你学会了 智力！',
    'You Learned Limebidextrous!': '你学会了 酸橙灵巧！',
    'Store 5x as many juicers': '存储 5 倍的榨汁机',
    'Store 5x as many peelers': '存储 5 倍的削皮器',
    'Store up to +1,000,000 coins': '最多可存储 +1,000,000 个硬币',
    'Pick up 2 limes rather than 1: +2% Chance.': '捡起 2 个酸橙而不是 1 个：+2% 几率。',
    'Pick up limes rather than rotten limes: +2% Chance.': '捡起酸橙而不是腐烂的酸橙：+2% 几率。',
    'Can collect limes.': '可以收集酸橙。',
    'Increases maximum juicers and peelers.': '增加最大榨汁机和削皮机。',
    'Keep 1,000 respect milestone after travelling': '旅行后保持 1,000 尊重里程碑',
    'Leave your items behind in search of a better town': '留下您的物品，寻找更好的城镇',
    'Reach level 100 to be able to toggle two actions at once.': '达到 100 级可以同时切换两个动作。',
    'Stop Actions': '停止操作',
    'Sublime by Becky': '酸橙经营者 by Becky',
    'Yes, i made a skill without a lime pun.': '是的，我创造了一项没有酸橙双关语的技能。',
    'Ambidextrous': '灵巧',
    'Chance to peel 2 limes rather than 1: +5%.': '剥 2 个酸橙而不是 1 个的几率：+5%。',
    'Change zoom size': '更改缩放大小',
    'Don\'t Confirm x5 Storage': '不确认 x5 存储',
    'Lime Disease': '酸橙病',
    'Dont let it spread from any civilian to any other': '不要让它从任何平民传播到任何其他人',
    'Doubles food points from eating.': '吃的食物点数翻倍。',
    'Employee is idle.': '员工处于闲置状态。',
    'Empty Baskets': '清空篮子',
    'Find places only the rich can go': '寻找只有富人才能去的地方',
    'For every lake used, gain / lose +1 respect': '每使用一个湖泊，获得/失去 +1 尊重',
    'Fork': '叉子',
    '5 Peeled Limes -> 1 Juice': '5 去皮酸橙 -> 1 果汁',
    'Automatically collects limes at 2': '自动收集酸橙2',
    'Can Collect Limes.': '可以收集酸橙。',
    'Allows your baskets to collect limes while you\'re away (offline).': '允许您的篮子在您离开（离线）时收集酸橙。',
    'Export Game (Plain': '导出存档（普通',
    'Increase the chance of finding limes rather than rotten limes.': '增加找到酸橙而不是腐烂酸橙的机会。',
    'Increase the chance of finding something rather than nothing when collecting limes.': '在收集酸橙时，增加找到东西的机会，而不是一无所有。',
    'Increase the chance of picking up double limes.': '增加捡到双酸橙的机会。',
    'Scarecrow': '稻草人',
    'Switch Variable Colors': '切换可变颜色',
    'Hyper Delivery': '究极交付',
    'Increase skilling speed.': '提高技能速度。',
    'Infinite Seconds': '无限秒',
    'Surveillance Camera': '监控摄像头',
    'Make sure employees are working while you\'re away (offline': '确保员工在您不在时（离线）工作',
    'Game': '游戏',
    'Change Zoom Size': '调整界面缩放尺寸',
    'UI': '界面',
    'Reach level 100 to be able to toggle two actions at once': '达到 100 级可以同时切换两个动作',
    'Think about those less fortuanate than you - unlocks Benevolence': '想想那些比你不幸的人——解锁仁慈',
    'Unlock the ability to hire currency brokers in the Hiring Area': '解锁在招聘区域雇佣货币经纪人的能力',
    'Yes, i made a skill without a lime pun': '是的，我创造了一项没有酸橙双关语的技能',
    'You use 1 food point per skill level': '技能每升一级，多使用 1 个食物点',
    'Your employee learns from your abilities': '您的员工从您的能力中学习',
    'Allows your baskets to collect limes while you\'re away (offline': '允许您的篮子在您离开时收集酸橙（离线',
    'Auto advertise unless speed is under 30 seconds': '自动广告，除非速度低于 30 秒',
    'Baskets collect 5 Limes per minute each': '每个篮子每分钟收集 5 个酸橙',
    'Baskets collect up to 25 Limes each': '每个篮子最多可收集 25 个酸橙',
    'Can collect limes': '可以收集酸橙',
    'Chance to peel 2 limes rather than 1: +5': '剥 2 个酸橙而不是 1 个的几率：+5',
    'Click the \'Teach\' button to start a timer': '单击“教学”按钮以启动计时器',
    'Click the application to accept': '点击申请接受',
    'Decreases peeled limes needed to make juice by 1': '将制作果汁所需的去皮酸橙减少 1',
    'Doubles food points from eating': '通过吃东西获得的食物点数翻倍',
    'Employee is idle': '员工闲着',
    'Increase disease tiles by 1': '将疾病板块增加 1',
    'High Tech Surveillance Camera': '高科技监控摄像机',
    'Increase respect change from helping civilians with more lakes': '通过帮助更多湖泊的平民来增加尊重变化',
    'Increase the chance of finding limes rather than rotten limes': '增加找到酸橙而不是烂酸橙的机会',
    'Increase skilling speed': '提高技能速度',
    'Increase the chance of finding something rather than nothing when collecting limes': '在收集酸橙时增加找到东西而不是一无所获的机会',
    'Increase the chance of picking up double limes': '增加捡到双酸橙的机会',
    'Increases max Mega Coins in the bank': '增加银行中的最大超级硬币',
    'Increases maximum juicers and peelers': '增加最大榨汁机和削皮机',
    'Increases the amount that motivation affects employees': '增加激励对员工的影响',
    'Juice price is saved after travelling': '旅行后保存果汁价格',
    'Make sure researchers are working while you\'re away (offline': '确保研究人员在您离开时工作（离线',
    'Make your employees as passionate about limes as you are': '让您的员工像您一样对酸橙充满热情',
    'Makes sure researchers are working while you\'re away': '确保研究人员在您离开时仍在工作',
    'Motivate Employee': '激励员工',
    'Motivation': '激励',
    '\"This tome will save you time on limes, 5 stars\"': '“这次可以节省你吃酸橙的时间，5 颗星”',
    '10 Alpha Coins -> 1 Mega Coin In Bank': '10 阿尔法硬币 -> 1 超级硬币在银行里',
    'Buy a Giant Map after only sending one delivery in that town': '只在该镇发送一次后购买一张巨型地图',
    'Get a 5x multplier with Buy More Land purchased': '购买购买更多土地获得 5 倍乘数',
    'A Safe On Wheels': '车轮上的保险箱',
    'Bring your alpha coins with you during your travels without pesky plebians stealing them': '在旅行期间随身携带您的 alpha 硬币，而不会被讨厌的平民偷走',
    'Buy Alpha Coin Rolls': '购买阿尔法硬币卷轴',
    'Cart researchers around rather than giving them any special attention': '推车研究人员而不是给予他们任何特别的关注',
    'Changes the max skill level for rotten wisdom to 25': '将腐烂智慧的最高技能等级更改为 25',
    'Keep alpha coins after travelling': '旅行后保留阿尔法币',
    'Lightweight Robe': '轻质长袍',
    'Respect +50 instantly after travelling': '旅行后立即尊重+50',
    'Rotten (Actual) Wisdom': '腐烂的（实际）智慧',
    'Safe On Wheels': '安全的轮子',
    'Transfer 10 Alpha Coins': '转账 10 个阿尔法币',
    'Unlock Bulk Researcher Transfer': '解锁批量研究员转账',
    'Unlocks bulk alpha coin -> mega coin transfer': '解锁批量阿尔法硬币 -> 大额硬币转账',
    '\t\tYou can keep playing and expanding your lime empire while you wait for new updates.': '\ t \ 您可以在等待新的更新的同时继续玩和扩大您的酸橙帝国。',
    'A farmer noticed you reselling pie, and thought you\'d like to purchase a field': '一个农民注意到你在转卖馅饼，并认为你想买一块地',
    "Accept your Lord's generosity": "接受主的慷慨",
    "Add Flour": "加入面粉",
    "Add Flour To Bucket": "将面粉加入桶中",
    "Add Juice": "添加果汁",
    "Add Juice To Bucket": "将果汁加入桶中",
    "Adjust the flour dropping rate for optimum performance": "调整面粉落下速度以获得最佳性能",
    "Adjust the juice dripping rate for optimum performance": "调整果汁滴落速度以获得最佳性能",
    "An orchardist recommends this new type of tree": "果园主推荐这种新型树",
    "Automatically drips juice into your pie": "自动将果汁滴入您的馅饼中",
    "Automatically drops flour into your pie": "自动将面粉放入馅饼中",
    "Automatically sends pies into the oven": "自动将馅饼送入烤箱",
    "Backpack": "背包",
    "Bake Pie": "烤馅饼",
    "Bakery": "面包店",
    "Basic Tree": "基础树",
    "Beta Coins": "贝塔硬币",
    "Bitter Speed": "苦味速度",
    "Bucket With A Hole": "有洞的桶",
    "Bulk Researcher Transfer": "批量研究人员转移",
    "Buy Alpha Coin Bags": "购买 阿尔法硬币袋",
    "Buy An Enormous Map": "购买一张巨大的地图",
    "Buy Another Bucket With A Hole": "再买一个有洞的桶",
    "Buy Another Nozzle": "再买一个喷嘴",
    "Buy Bellows": "购买风箱",
    "Buy Pie": "购买馅饼",
    "Buy Thin Steel Plating": "购买薄钢板",
    "Can grinding ever be fun?": "磨削真的很有趣吗？",
    "Click on the customer to sell to them before they become unhappy and leave!": "在客户不高兴离开之前点击客户向他们出售！",
    "Close": "关闭",
    "Continue": "继续",
    "Convert Alpha Coins to Beta Coins": "将 阿尔法 币转换为 贝塔 币",
    "Converts Alpha Coins to Beta Coins if the conversion rate is below 1,000": "如果转换率低于 1,000，则将 阿尔法 币转换为 贝塔 币",
    "Conveyor Belt": "传送带",
    "Currency Broker": "货币经纪人",
    "Decrease Price": "降价",
    "Does what it says on the label": "是否符合标签上的要求",
    "Don't Toggle": "不要切换",
    "Button Option": "按钮选项",
    "Shift Click": "Shift + 点击",
    "Donate": "捐赠",
    "Eat A Golden Lime": "吃一个金酸橙",
    "Eat Rice": "吃米饭",
    "Enter": "进入",
    "Enter The Well": "进入井",
    "Every level increases that effect's length.": "每个级别都会增加该效果的长度。",
    "Field": "场地",
    "Get access to mega coins in this town, but takes twice as long every time": "在这个城镇获得超级硬币，但每次需要两倍的时间",
    "Give your lord rice": "给你的主米饭",
    "Go through pie merchant applications in the Hiring Area": "通过招聘区域的馅饼商人应用程序",
    "Golden Lime Tree": "金酸橙树",
    "Golden Limes": "金酸橙",
    "Golden limes slowly rot away once you collect them": "一旦你收集它们，金酸橙就会慢慢腐烂",
    "Golden Tome": "金卷轴",
    "Grind Seeds Into Flour": "将种子磨成面粉",
    "Harvest Rice": "收获水稻",
    "Harvester": "收割机",
    "Hire A Trainer": "聘请培训师",
    "Hire An Employee": "雇用一名员工",
    "Hire Basic Alpha Coin -> Beta Coin Broker": "雇用基础 阿尔法硬币 -> 贝塔硬币经纪人",
    "Hire someone to convert for you": "雇用某人为您转换",
    "Increase Price": "提高价格",
    "Increases customer acquisition speed": "提升顾客获取速度",
    "Increases oven speed by adding more oxygen": "通过添加更多氧气来提高烤箱速度",
    "Is wheat the new lime?": "小麦是新酸橙吗？",
    "Lowers the max skill level of Rotten Wisdom from 50 to 25": "将腐化智慧的最高技能等级从 50 降低至 25",
    "Manage Plot": "管理地块",
    "Mortar And Pestle": "研钵和研杵",
    "New Bakery": "新面包店",
    "New Tree": "新树",
    "Nozzle": "喷嘴",
    "One step closer to pie creation": "离创造馅饼又近了一步",
    "Pay Employee 5 Pie Coins": "支付员工 5 个馅饼币",
    "Open up a new bakery in the rough part of town": "在城镇的崎岖地区开设一家新面包店",
    "Perfect for extending the height of your buckets": "非常适合扩展您的水桶高度",
    "Pie Coins": "馅饼币",
    "Pie Conveyor Belt": "馅饼传送带",
    "Pie is essential for the patrician diet": "馅饼是贵族饮食必不可少的",
    "Pie Merchant": "馅饼商人",
    "Pie Oven": "馅饼烤箱",
    "Pies": "馅饼",
    "Put your face on a billboard so people know who helped them": "把你的脸贴在广告牌上，让人们知道谁帮助了他们",
    "Reach level 20 to be able to toggle two actions at once": "达到 20 级可以同时切换两个动作",
    "Respect Billboard": "尊重广告牌",
    "Rice": "米",
    "Rotate": "旋转",
    "Search for customers": "寻找客户",
    "Seed": "种子",
    "Seed Drill": "播种机",
    "Sell Pies": "出售馅饼",
    "Sell Rice": "出售大米",
    "Serf": "农奴",
    "Show Beta Coins": "显示 贝塔币",
    "Show Beta Coins": "显示 贝塔币",
    "Show Coins": "显示 硬币",
    "Show Golden Limes": "显示 金酸橙",
    "Show Juice": "显示 果汁",
    "Show Mega Coins": "显示 超级硬币",
    "Show Peeled Limes": "显示 去皮酸橙",
    "Show Pie Coins": "显示 馅饼币",
    "Show Pies": "显示 馅饼",
    "Show Rotten Limes": "显示 烂酸橙",
    "Specifically lime peeling and juicing.": "特别是酸橙去皮和榨汁。",
    "Start Selling Pie": "开始卖馅饼",
    "Sublime": "酸橙",
    "The bitterness of the golden limes increases your abilities!": "金酸橙的苦味会增加你的能力！",
    "The lower the price the faster you find customers": "价格越低，找到客户的速度就越快",
    "The orchardist says those limes are useful for something...": "果园主说这些酸橙对某些东西很有用......",
    "These bags help you convert more coins at a time": "这些袋子可帮助您一次转换更多硬币",
    "These map prices are getting absurd...": "这些地图价格越来越荒谬了......",
    "These new nozzles allow for finer tuning": "这些新喷嘴允许进行更精细的调整",
    "This is sow useful!": "这对母猪有用！",
    "This person will give the pie to the customer, but must be paid.": "这个人会把馅饼给顾客，但必须付钱。",
    "This trainer will help you to instantly complete a skill's level": "这位训练者将帮助您立即完成技能等级",
    "Throw Pie Coins In The Well": "往井里扔馅饼币",
    "Train Delivery": "训练送货",
    "Train Transport": "训练运输",
    "Transfer Alpha Coins x10": "转移阿尔法币 x10",
    "Unlock Advanced Pie Hiring": "解锁高级馅饼招聘",
    "Upgrade Nozzles": "升级喷嘴",
    "Use Bellows": "使用风箱",
    "Water is the lifeblood of limes": "水是酸橙的生命线",
    "Well": "水井",
    "Wheat Harvester": "小麦收割机",
    "Wheat Seed": "小麦种子",
    "Winnow Wheat": "温诺小麦",
    "You completed Sublime!! Good job! :": "你完成了 酸橙经营者 ！！ 做得好！ ：",
    "Your soul hangs in a void with a field of wells.\n\t\tEnter one.": "你的灵魂悬在一片空旷的井中。\N\t\t进入一个。",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",

    //树游戏
    'Loading...': '加载中...',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "(-": "(-",
    "(+": "(+",
    "(": "(",
    "-": "-",
    "+": "+",
    " ": " ",
    ": ": "： ",
    "\n": "",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    "Currently: ": "当前: ",
    "Current Employees: ": "当前员工: ",
    'Buy A ': '购买一个 ',
    "Current increase: ": "当前增加: ",
    "Current maximum: ": "当前最大值：",
    "Current speed: ": "当前速度：",
    "Disease Tiles: ": "疾病板块：",
    "Disease Tiles ": "疾病板块",
    "Skilling speed: ": "技能速度：",
    "Skills: ": "技能: ",
    "Speed: ": "速度: ",
    "Aesthetic: ": "审美：",
    "Total Price: ": "总价: ",
    "Transfer Fee: ": "转账费: ",
    "You Need: ": "你需要: ",
    "Doubles juice sale price": "果汁销售价格翻倍",
    "Goal: ": "目标: ",
    "Hunger: ": "饥饿：",
    "Increases maximum applicant speed by ": "增加了最大申请人速度",
    "Increases maximum coin storage by ": "将最大硬币存储量增加",
    "Price: ": "价格: ",
    "Level ": "等级 ",
    "Number of civilians:": "平民人数：",
    "Number of Civilians:": "平民人数：",
    "Number Of Civilians:": "平民人数：",
    "Transfer times: ": "转账次数: ",
    "Wage: ": "工资：",
    "Wages: ": "工资：",
    "Current Speed: ": "当前速度: ",
    "Disease type: ": "疾病类型：",
    'Estimated Time: ': '预计的时间：',
    "Exchange Rate: ": "汇率：",
    "Working time left:": "工作时间剩余:",
    "Respect increase:": "尊重增加：",
    "Increases maximum juicers by ": "增加最大榨汁机 ",
    "Available Seed Drills: ": "可用的播种机：",
    "Available Wheat Harvesters: ": "可用的小麦收割机：",
    "Beta Coin Wages: ": "贝塔硬币工资：",
    "Charm: ": "吸引力：",
    "Current Ingredients: ": "当前成分：",
    "Current Price: ": "当前价格: ",
    "Don't Toggle: ": "不要切换：",
    "Employee Sales Left: ": "剩余员工销售额：",
    "Hiring Price: ": "雇佣价格: ",
    "Flour: ": "面粉: ",
    "Lord's coins: ": "领主硬币：",
    "Lord's rice: ": "领主的米：",
    "Max Wage Advances: ": "最高工资预支：",
    "Pie Coin Wages: ": "馅饼币工资：",
    "Rice owed: ": "大米欠款：",
    "Seeds: ": "种子: ",
    "The lord is pleased": "主人很高兴",
    "True Limes: ": "真正的酸橙：",
    "Wheat: ": "小麦: ",
    "You are healthy": "你很健康",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    ":": "：",
    "：": "：",
    ": ": "： ",
    "： ": "： ",
    "/s)": "/s)",
    "/s": "/s",
    ")": ")",
    "%": "%",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": " ",
    "\n": "",
    " Available Researchers": "现有研究人员",
    "Respect: ???": "尊重: ???",
    "Respect: Unlock scientific research": "尊重: 解锁科研",
    "Respect: Automatically start tasks": "尊重: 自动启动任务",
    "Respect: Unlock more mega coin upgrades": "尊重: 解锁更多超级硬币升级",
    "Respect: Automatically check simulation": "尊重: 自动检查模拟",
    "Respect: Automatically start simulation": "尊重: 自动开始模拟",
    "Respect: Allow entrance to the Special Shopping District": "尊重: 允许进入特殊购物区",
    "Respect: Automatically situate a civilian": "尊重: 自动定位一个平民",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^([\d\.,]+)$/,
    /^ ([\d\.,]+)$/,
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^[\u4E00-\u9FA5]+$/,
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
    [/^You Need ([\d\.,]+) Coins For Delivery$/, '您需要 $1 枚硬币才能交付'],
    [/^ ([\d\.,]+) \/ ([\d\.,]+) minutes.$/, ' $1 \/ $2 分钟。'],
    [/^\-([\d\.,]+) limes per minute.$/, '\-$1 酸橙每分钟。'],
    [/^([\d\.,]+)\% Profit$/, '$1\% 利润'],
    [/^Total Time Played: (.+) Seconds$/, '总游戏时长：$1 秒'],
    [/^([\d\.,]+) baskets fit under the current tree$/, '当前树下可容纳 $1 个篮子'],
    [/^([\d\.,]+) seconds$/, '$1 秒'],
    [/^(.+)\% Of What I'm Taught$/, '我所教内容的 $1\%'],
    [/^([\d\.,]+) limes per minute.$/, '$1 酸橙分钟。'],
    [/^([\d\.,]+) Limes per second.$/, '$1 酸橙每秒。'],
    [/^([\d\.,]+) Limes Per Second$/, '$1 酸橙每秒'],
    [/^([\d\.,]+) Limes Per Second.$/, '$1 酸橙每秒。'],
    [/^([\d\.,]+) Coins Per Minute.$/, '$1 硬币每分钟。'],
    [/^([\d\.,]+) Coins Per Minute$/, '$1 硬币每分钟'],
    [/^([\d\.,]+) Coins per minute.$/, '$1 硬币每分钟。'],
    [/^([\d\.,]+) limes per minute$/, '$1 酸橙每分钟'],
    [/^([\d\.,]+) seconds.$/, '$1 秒。'],
    [/^([\d\.,]+) Tiles$/, '$1 板块'],
    [/^([\d\.,]+) Basket$/, '$1 篮子'],
    [/^([\d\.,]+) Juicers$/, '$1 榨汁机'],
    [/^([\d\.,]+) Mega Coin$/, '$1 超级硬币'],
    [/^([\d\.,]+) Respect$/, '$1 尊重'],
    [/^([\d\.,]+) Peeler$/, '$1 削皮器'],
    [/^([\d\.,]+) Alpha Coins$/, '$1 阿尔法硬币'],
    [/^([\d\.,]+) Mega Coins$/, '$1 超级硬币'],
    [/^([\d\.,]+) Beta Coins$/, '$1 贝塔硬币'],
    [/^([\d\.,]+) Coins.$/, '$1 硬币。'],
    [/^([\d\.,]+) Coins$/, '$1 硬币'],
    [/^([\d\.,]+) Coin$/, '$1 硬币'],
    [/^([\d\.,]+) Limes$/, '$1 酸橙'],
    [/^([\d\.,]+) Minutes$/, '$1 分钟'],
    [/^Increases maximum peelers by ([\d\.,]+)$/, '最大榨汁机数量增加 $1'],
    [/^([\d\.,]+)\% Of What I\'m Taught.$/, '我所教内容的 $1\%。'],
    [/^([\d\.,]+) Peeled Limes \-> ([\d\.,]+) Juice$/, '$1 去皮酸橙 \-> $2 果汁'],
    [/^([\d\.,]+) Limes \-> ([\d\.,]+) Juice$/, '$1 酸橙 \-> $2 果汁'],
    [/^([\d\.,]+) Coins \-> ([\d\.,]+) Mega Coins in the bank$/, '$1 硬币 \-> $2 银行里的超级硬币'],
    [/^([\d\.,]+) Coins \-> ([\d\.,]+) Alpha Coin$/, '$1 硬币 \-> $2 阿尔法硬币'],
    [/^([\d\.,]+) Coins \-> ([\d\.,]+) Mega Coin now$/, '$1 硬币 \-> $2 超级硬币现在'],
    [/^([\d\.,]+) Alpha Coins \-> ([\d\.,]+) Mega Coin$/, '$1 阿尔法硬币 \-> $2 超级硬币'],
    [/^([\d\.,]+) Alpha Coins \-> ([\d\.,]+) Beta Coin$/, '$1 阿尔法硬币 \-> $2 贝塔硬币'],
    [/^([\d\.,]+) \/ ([\d\.,]+) Tiles$/, '$1 \/ $2 板块'],
    [/^([\d\.,]+) \/ ([\d\.,]+) Peelers$/, '$1 \/ $2 削皮器'],
    [/^([\d\.,]+) \/ ([\d\.,]+) Baskets$/, '$1 \/ $2 篮子'],
    [/^([\d\.,]+) \/ ([\d\.,]+) Juicers$/, '$1 \/ $2 榨汁机'],
    [/^([\d\.,]+) \/ ([\d\.,]+) Mega Coins In Bank$/, '$1 \/ $2 银行里的超级硬币'],
    [/^Collect ([\d\.,]+) Coins.$/, '收集 $1 硬币。'],
    [/^Collect ([\d\.,]+) Coins$/, '收集 $1 硬币。'],
    [/^Price: ([\d\.,]+) Coins$/, '价格: $1 硬币'],
    [/^Price: ([\d\.,]+) Alpha Coins$/, '价格: $1 阿尔法硬币'],
    [/^Price: ([\d\.,]+) Mega Coins$/, '价格: $1 超级硬币'],
    [/^Store up to (.+) Mega Coins in your bank account$/, '在您的银行账户中存储多达 $1 超级硬币'],
    [/^You Need (.+) Juice$/, '你需要 $1 果汁'],
    [/^You Need (.+) Limes$/, '你需要 $1 酸橙'],
    [/^You Will Deliver (.+) Juice$/, '您将提供 $1 果汁'],
    [/^Currently (.+) \- (.+) Alpha Coins$/, '当前 $1 \- $2 阿尔法硬币'],
    [/^Currently (.+) \- (.+) Coins$/, '当前 $1 \- $2 硬币'],
    [/^Currently (.+) \- (.+) Seconds$/, '当前 $1 \- $2 秒'],
    [/^([\d\.]+) Respect$/, '$1 尊重'],
    [/^([\d\.]+) baskets fit under the current tree.$/, '当前树下可容纳 $1 个篮子。'],
    [/^([\d\.]+) Researchers$/, '$1 研究人员'],
    [/^([\d\.]+) Mega Coins In Bank$/, '$1 银行里的超级硬币'],
    [/^([\d\.]+) Flour \+ ([\d\.]+) Juice$/, '$1 面粉 \+ $2 果汁'],
    [/^([\d\.]+) Juice \+ ([\d\.]+) Flour$/, '$1 果汁 \+ $2 面粉'],
    [/^([\d\.]+) Pie Coin$/, '$1 馅饼币'],
    [/^([\d\.]+) Beta Coin$/, '$1 贝塔币'],
    [/^([\d\.]+) Pie Coins$/, '$1 馅饼币'],
    [/^([\d\.]+) Beta Coins$/, '$1 贝塔币'],
    [/^Increase for ([\d\.]+) Pie Coins$/, '提高 $1 馅饼币'],
    [/^([\d\.]+) Limes$/, '$1 酸橙'],
    [/^([\d\.]+) Lakes$/, '$1 湖泊'],
    [/^([\d\.]+) Limes.$/, '$1 酸橙。'],
    [/^([\d\.]+) Limes per minute.$/, '$1 酸橙每分钟。'],
    [/^(.+)\% Chance$/, '$1\% 几率'],
    [/^(.+)\% Faster$/, '$1\% 更快'],
    [/^You Will Get (.+) Coins$/, '你将获得 $1 硬币'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
    [/^Reward: (.+) Coin$/, '奖励：$1 硬币'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^(\d+) Royal points$/, '$1 皇家点数'],
    [/^Current heights: (.+) Units$/, '当前高度：$1 单位'],
    [/^Cost: (\d+) RP$/, '成本：$1 皇家点数'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);